### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'circos'

### ISSUE THREAD

**Issue by ericgonzalezs** [AntoineHo/CircosAlignmentPlotter#2]
Hi, 

I created a python virtual environment with python3.11, and I installed 
    biopython
    circos
    pandas
    numpy
With pip install.

I am running the program like this:

p2c.py H1_MojtabaGaps.paf  ANN1372_H1_H2_hap1.reviewed.chr_assembled.fasta VIGUIERA_H1_H2.reviewed.chr_assembled.fasta  VIGUIERA_H1_H2.reviewed.chr_assembled.fasta.bed PLOT_RESULTS

I am having the next error.

Query: /lustre07/scratch/egonza02/ASSEMBLIES/SCAFFOLDING/CPU_MODE/MAKE_FASTAS/SECOND_TRY/VIGUIERA_G_AFTER_REVIEW/VISUALIZE/ANN1372_H1_H2_hap1.reviewed.chr_assembled.fasta
Reference: /lustre07/scratch/egonza02/ASSEMBLIES/SCAFFOLDING/CPU_MODE/MAKE_FASTAS/SECOND_TRY/VIGUIERA_G_AFTER_REVIEW/VISUALIZE/VIGUIERA_H1_H2.reviewed.chr_assembled.fasta
Targets: /lustre07/scratch/egonza02/ASSEMBLIES/SCAFFOLDING/CPU_MODE/MAKE_FASTAS/SECOND_TRY/VIGUIERA_G_AFTER_REVIEW/VISUALIZE/VIGUIERA_H1_H2.reviewed.chr_assembled.fasta.bed
PAF: /lustre07/scratch/egonza02/ASSEMBLIES/SCAFFOLDING/CPU_MODE/MAKE_FASTAS/SECOND_TRY/VIGUIERA_G_AFTER_REVIEW/VISUALIZE/H1_MojtabaGaps.paf
Outdir: /lustre07/scratch/egonza02/ASSEMBLIES/SCAFFOLDING/CPU_MODE/MAKE_FASTAS/SECOND_TRY/VIGUIERA_G_AFTER_REVIEW/VISUALIZE/PLOT_RESULTS
Templates: /lustre07/scratch/egonza02/SOFTWARE/CircosAlignmentPlotter/CircosAlignmentPlotter/templates
Copying files...
Building karyotype.txt...
Building links.txt...
Building highlights.txt...
Adding samtools formatted coverage...
Adding circos formatted coverage...
Running circos in /lustre07/scratch/egonza02/ASSEMBLIES/SCAFFOLDING/CPU_MODE/MAKE_FASTAS/SECOND_TRY/VIGUIERA_G_AFTER_REVIEW/VISUALIZE/PLOT_RESULTS
Traceback (most recent call last):
  File "/home/egonza02/scratch/SOFTWARE/CircosAlignmentPlotter/CircosAlignmentPlotter/p2c.py", line 473, in <module>
    main()
  File "/home/egonza02/scratch/SOFTWARE/CircosAlignmentPlotter/CircosAlignmentPlotter/p2c.py", line 470, in main
    plotPAF(dAlns, iFH.outdir, iFH.templates, iFH.query, iFH.reference, correspondance, min_len, contigs_lengths, targets_to_plot, bed=iFH.bed, scov=iFH.scov, ccov=iFH.ccov, snps=iFH.snps)
  File "/home/egonza02/scratch/SOFTWARE/CircosAlignmentPlotter/CircosAlignmentPlotter/p2c.py", line 410, in plotPAF
    run(cmd)
  File "/home/egonza02/scratch/SOFTWARE/CircosAlignmentPlotter/CircosAlignmentPlotter/p2c.py", line 415, in run
    proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.11.2/lib/python3.11/subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.11.2/lib/python3.11/subprocess.py", line 1901, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'circos'

Do you know how I could solve this error?

Thanks,

Eric

**Comment by AntoineHo** [comment]
Hello,

Given the error message, I think it comes from a problem of either circos or from the python subprocess package that calls to circos.

Because this is the last step of the pipeline, you can try to run it manually by going into this directory: `cd /lustre07/scratch/egonza02/ASSEMBLIES/SCAFFOLDING/CPU_MODE/MAKE_FASTAS/SECOND_TRY/VIGUIERA_G_AFTER_REVIEW/VISUALIZE/PLOT_RESULTS` and just running `circos`, it should find the config file in the directory. (If this fails because the config file was not specified, you can also try with `circos -c circos.conf`).

If you still get an error, then it could be that circos is not installed in the environment or a problem with "subprocess", maybe installing another version of python (I just tried the pipeline with python 3.11.4 and it worked fine).

Best,

Antoine
